### ISSUE TITLE
Image-Sender + Receiver only synchronizes first 10 images on linux

### ISSUE THREAD

**Issue by arcvid** [ni/adas-replay-hil-image-shim#6] opened 2022-11-08 06:21 UTC
After using this fix https://github.com/ni/adas-replay-hil-image-shim/pull/4, the customer is having an issue with the imageSender + Receiver on linux 
Attaching a video and main.cpp
Here is the issue description as provided by customer:
---------------------------------------------------------------------------------------------------------------------------------------------------
Setup:
0. ImageSender (shim) running on Linux Ubuntu (x64)
1. VideoReceiver executable (running on PXI). This is not the VI, this is the actual executable in the [release](https://urldefense.com/v3/__https:/github.com/ni/adas-replay-hil-image-shim/releases/tag/v22.0.0d401__;!!FbZ0ZwI3Qg!rqjOHx9xfCFwttgdBs9u8eR8IV57JLTyis-1MnlZ-ONFj7CjkTd8g8Y3Im8oobEMibB6cWuYp9qcRWaC9yG10uQ$)

Details:
0. Able to reproduce this directly with image shim. I have only added two std::cout's in the main.cpp (attached)
1. After the 10th image, the image-receiver times out, and the sender does not exit (it attempt to send the image).
2. I have tried changing the timeout for the image sender, but the call to session.SendImage does not return no matter how short or long the timeout is
3. We are able to reproduce this issue with our own replay-framework that wraps around the libimageSender.so (NI Image Sender).

Suggestions:
I am quite sure NI has a newer version of either libnirdma.so.1 or libimageSender.so or the VideoReceiver. I am running libimageSender.so version 22.0 (latest). 

SHA-1 Hashes of files I am using
(PXI) VideoReceiver: e6219056ad74d3b966bc085633bab6bbefdb2eb2
(Ubuntu) ImageSenderLib/libimageSender.so e563237e190c670b4c76250eb7e98fc66bd9ab5f 
(Ubuntu) libnirdma.so.1. afd315a5d0304812614a97694e49f7f0e0f6eb18 

https://user-images.githubusercontent.com/99898758/200488857-8100efb2-5233-4b8a-bd8d-26fc1ff1b057.mov

[main.zip](https://github.com/ni/adas-replay-hil-image-shim/files/9958233/main.zip)

**Comment by gaoruhao** [comment] 2022-11-08 14:19
@arcvid Assigned this issue to @YangLiuNI. Some quick comments here:
- The videoReceiver and ImageSender library published here are the latest ones. We don't have a newer version internally.
- NI RDMA does not newer unreleased version 23.0. We also asked our internal users to install NI RDMA 23.0 daily build, but I am not sure if you can share the internal NI RDMA builds with customers.

**Comment by YangLiuNI** [comment] 2022-11-08 14:50
@arcvid There was a bug in libnirdma, the bug will cause the RDMA transmission hang there after sending several frames, the bug should be fixed in libnirdma 22.8, so could you update libnirdma so 23.0 and try again?
[libnirdma.so.23.0.zip](https://github.com/ni/adas-replay-hil-image-shim/files/9962279/libnirdma.so.23.0.zip)

**Comment by arcvid** [comment] 2022-11-08 14:55
@gaoruhao, thank you for the response. 
I already shared the  daily Installer for NI RDMA 23.0 to the customer. 

@YangLiuNI, I will share the libnirdma.so.23.0.zip with customer. 
NI RDMA 23.0 should be installed along with the libnirdma provided here. 
Is this sufficient?

**Comment by arcvid** [comment] 2022-11-08 22:43
After having a screenshare with the customer on this, especially after they used the **libnirdma.so.23.0**, this is the status:

1. When using libnirdma.so.23.0 on both Sender and Receiver, a segmentation fault is noticed immediately after the connection is established. Not a single image was sent.
2. Receiver is Linux RT PXI. Sender is Linux x64 Ubuntu. 
3. NI RDMA 23.0 - installing this did not help to update the version on the Receiver Linux RT PXI

More details:
With the new version (23.0), the sender side segfaults after establishing a
 connection. The receiver spits out an error that it was disconnected. Please see the issue noticed/with screenshot.  
Is this issue on the sender side, and the receiver just complained because the sender segfaulted and closed the connection abruptly?
![using23 0_segfault](https://user-images.githubusercontent.com/99898758/200690706-fdea7009-074a-4130-b6ab-639df9b5cffa.PNG)

With the old version (22.0) 
the sender sends 10 images and hangs on the 11th image. The receiver waits for that 11th image and after a timeout, the receiver gives up and closes the connection with an error in line 113 on Rdmabufferqueue.cpp
![using22 0_operationtimedout](https://user-images.githubusercontent.com/99898758/200691763-fdb43ad7-d92f-4c60-bee3-68004ce9b17c.PNG)

**Comment by YangLiuNI** [comment] 2022-11-09 01:27
Hmm, I am not able to reproduce on my Linux environment
Sender: Ubuntu 20.04.4 LTS/libnirdma 23.0
Receiver:  NI Linux Real-Time 9.1/libnirdma 23.0
![image](https://user-images.githubusercontent.com/105096128/200713057-7fd8b130-fe60-4b97-b3ce-c02d5597d1b8.png)
![image](https://user-images.githubusercontent.com/105096128/200713116-21ac6a99-6717-417f-85e1-ebb4126c5a60.png)

I am not sure if the customer environment is correctly set up.
So let's try to break this issue down, Could you try to run both sender and receiver on your Ubuntu machine first(Loopback the RDMA data stream on same RDMA card) and see if it works? Thanks

**Comment by arcvid** [comment] 2022-11-09 03:36
Hi @YangLiu
I dont have an Ubuntu machine to try this on at the moment. Short on RDMA cards as well.
Before I do that, I wanted to ask if you can share what libimageSender version you're using and also the folder structure of adas-replay-image-shim repo. 

Could you please also share how you're running videoReceiver?

**Comment by YangLiuNI** [comment] 2022-11-09 03:57
@arcvid I am using v22.0.0d395, the repo structure is as follows
![image](https://user-images.githubusercontent.com/105096128/200734821-0a0ecfbe-f796-49e0-a977-5fc6f717831d.png)

For videoReceiver command
![image](https://user-images.githubusercontent.com/105096128/200734904-f165ef81-3478-4549-ab9e-1430bf40ac88.png)

**Comment by arcvid** [comment] 2022-11-09 05:49
Thanks for the files. I've checked that the folder structure is correct based on a previous screenshot from customer. 
Requesting your feedback on the following:

1. With the attached zip here, the customer is able to run the imageSender for 10 images after which there is an Operation timed out error reported. 
[10ImagesAndDone.zip](https://github.com/ni/adas-replay-hil-image-shim/files/9967664/10ImagesAndDone.zip)
In this case, 10 images are sent. When using libnirdma 23.0 today, the error reported is 'Disconnected' & no images are sent. 
How is this libimageSender different from the one you're using? 
Could you please share that libimageSender.so which you're using? 

2. Is the default outputFormat YUV422? Have you already been able to check if your setup works when you mention outputFormat YUV422?

3. What do you refer to when you said the environment of the customer is not setup correctly? This is the https://github.com/ni/adas-replay-hil-image-shim/tree/main/example/imageSender#readme file used for setting up this adas-replay-hil-image-shim repo
What could I use to verify the environment is setup correctly?

**Comment by YangLiuNI** [comment] 2022-11-09 06:12
1. The libimageSender.so is a symbol link to the one libimageSender.so.22.0.0 in https://github.com/ni/adas-replay-hil-image-shim/releases/tag/v22.0.0d395, this is how I create it:
![image](https://user-images.githubusercontent.com/105096128/200752343-c8c0efbf-73ab-4efd-8d36-d1dc27b246d9.png)

2. Yes the default outputFormat is YUV422, if I specify it explicitly I am able to send and receive as well
![image](https://user-images.githubusercontent.com/105096128/200752523-eda6a879-33b8-46f4-9b58-68467ec68b64.png)

3. I mean you should install corresponding OFED(https://network.nvidia.com/products/infiniband-drivers/linux/mlnx_ofed/) according to your RDMA card model first, and you should also make sure you are using libnirdma 23.0.0

Is it possible for us to remote connect to user's server to check what happens?

**Comment by arcvid** [comment] 2022-11-09 06:50
1. Thanks for showing that. From what I understand customer's using release version: https://github.com/ni/adas-replay-hil-image-shim/releases/tag/v22.0.0d401
2. Ok
3. Will check on the OFED. But we did use the libnirdma 23.0 when we had our discussion. 

Remote connect without any customer inputs OR Screenshare and figure out issue?
Please let me know time so I can set it up. They are in California.

**Comment by YangLiuNI** [comment] 2022-11-09 07:12
For libnirdma ==>

On ubuntu desktop, currently we don't have an installer for Linux so you have so save the libnirdma.so.23.0.0 somewhere in your system, and make sure it is under your system's library search path, you can make sure the library search path by the following command
```ld --verbose | grep SEARCH_DIR | tr -s ' ;'```
Then you create a symbol link for the library manually by 
```ln -s libnirdma.so.23.0.0 libnirdma.so.1```

On PXI system, you should install NI-RDMA through the feed http://argohttp.natinst.com/ni/linuxpkg/feeds/ipk/ni-r/ni-rdma/23.0.0/23.0.0.45-0+d45/inline/

I am thinking to remote connect without customer input, if they can create an account for us then we can just login their system to check if everything is installed well or debug what is the root cause, but not sure if they have any concern for this, e.g. security concern.

**Comment by arcvid** [comment] 2022-11-09 07:48
Ubuntu desktop - from what I recall, the customer saved the libnirdma similar to where you have saved under /usr/lib but I’ll check once more 

Will send the link to the customer for installing on linux RT PXI. 

Also, I checked  regarding the remote login. There’s a code that resets every 10 mins so I need to check if there’s a better remote login option from them. 
if not, the only way we can do this is to setup a time to remote login with you and the customer so that they’re  able to keep the session active.

**Comment by arcvid** [comment] 2022-11-09 21:50
Hi @YangLiuNI 
Customer confirmed the following:
1. libnirdma is stored and located in LD_PATH.
2. OFED/all infiniband drivers are installed
3. Sent this ipk file to them for installing RDMA on PXI RT. Please Let me know if any other ipk files in the link need to be shared.
[ni-rdma_23.0.0.45-0+d45_x64-PXI.ipk.zip](https://github.com/ni/adas-replay-hil-image-shim/files/9975330/ni-rdma_23.0.0.45-0%2Bd45_x64-PXI.ipk.zip)

4. For the remote login, due to security concerns they are only ok with screenshare + full control to you. 
**Could you please provide timings that you are available to do this screenshare call? 
On 10th November & 11th November as per Shanghai time morning and Evening?**

**Comment by YangLiuNI** [comment] 2022-11-10 01:12
Hi @arcvid, what about 11th Nov, at 9:00 Shanghai time / 17:00 California time?

**Comment by arcvid** [comment] 2022-11-10 03:20
Confirmed, setting up the meeting.

**Comment by arcvid** [comment] 2022-11-11 01:51
@YangLiuNI, thank you for joining the session with the customer. Here is the summary: 

1.This [release ](https://github.com/ni/adas-replay-hil-image-shim/releases/tag/v22.0.0d422)was used during the session. 
-One recommendation is to unzip the folder, instead of manually creating subfolders. libnirdma 23.0 was already saved.
-so file was created using `ln -s libimageSender.so.22.0.0 libimageSender.so`

**Feedback from customer/Learnings:**
1. Dependencies should be included with the releases itself. For example, libnirdma 23.0 was sent via email. 
2. Change log for each release under [Releases ](https://github.com/ni/adas-replay-hil-image-shim/releases/tag/v22.0.0d422)can be mentioned to know what has changed between one version to another
3. Is the exception `Disconnected` going to be handled in the next release?
![image](https://user-images.githubusercontent.com/99898758/201244517-60956d40-3a35-4245-9d92-bb80947a39e3.png)

4. Linux RT does not have ldd so on VideoReceiver we cannot see what symbols are being used. Could this be useful to include? 

@gaoruhao, thank you for your support. Please let me know if I need to start a new GitHub discussion for the feedback/learnings.

**Comment by ericgross2** [comment] 2022-11-11 02:42
@arcvid Some comments:
-The team that maintains NI-RDMA is preparing a release version with all the updates we need. Once that is available it should be in the standard package feeds that Linux RT can install online or offline. Note that this is only for Linux RT (PXI). Some effort on NI's side is still needed on how best to distribute binaries for Linux desktop, as currently that is not supported by installers.

-I'm not entirely sure of the context of the exception shown, but I imagine it is expected. Both videoReceiver and that image sender dll example both use exceptions to signal the disconnect event along with any other event/error. It doesn't know whether the disconnect is intentional or not.

-On linux RT, you can use 'opkg update && opkg install ldd" to get ldd installed. There's a wealth of standard linux packages supported by the upstream OpenEmbedded distribution it is based on.

**Comment by arcvid** [comment] 2022-11-11 03:30
> @arcvid Some comments: -The team that maintains NI-RDMA is preparing a release version with all the updates we need. Once that is available it should be in the standard package feeds that Linux RT can install online or offline. Note that this is only for Linux RT (PXI). Some effort on NI's side is still needed on how best to distribute binaries for Linux desktop, as currently that is not supported by installers.
> 
> -I'm not entirely sure of the context of the exception shown, but I imagine it is expected. Both videoReceiver and that image sender dll example both use exceptions to signal the disconnect event along with any other event/error. It doesn't know whether the disconnect is intentional or not.
> 
> -On linux RT, you can use 'opkg update && opkg install ldd" to get ldd installed. There's a wealth of standard linux packages supported by the upstream OpenEmbedded distribution it is based on.

Thanks Eric. 
For NI-RDMA, in that case what would be the best way to link a particular version of libnirdma with a particular tagged release? Even the feeds argo link is internal.
OK for 2, 3.

**Comment by ericgross2** [comment] 2022-11-11 04:59
Ni-RDMA is always backwards compatible, so it is only necessary to update if there are bug fixes that are needed.

**Closed** 2022-11-15 02:36 UTC
